vim.keymap.set("n", "<F5>", function()
  local args = vim.fn.input("CLI Args: ")
  vim.cmd("vsplit | term python % " .. args)
  vim.cmd("stopinsert")
end, { buffer = true, desc = "Run Python script in NeoVim" })
